### ISSUE TITLE
numeric sum up bug

### ISSUE THREAD

**Issue by ZZzzGeorge** [jwadhams/json-logic#18]
Rule:
{
      "+": [
        { "var": "RATE_1" },
        { "var": "RATE_2" }
      ]
}

Data1 : 36.54+22.309 expected 58.849, but actual 58.849000000000004
{
"RATE_1": 36.54,
"RATE_2": 22.309
}
Data2 : 36.54+22.308 expected 58.848, actual 58.848 ----- OK
{
"RATE_1": 36.54,
"RATE_2": 22.308
}
Data3 : 36.54+22.307 expected 58.847, but actual 58.846999999999994
{
"RATE_1": 36.54,
"RATE_2": 22.307
}
Data4 : 36.54+22.306 expected 58.846, but actual 58.846000000000004
{
"RATE_1": 36.54,
"RATE_2": 22.306
}
Data5 : 36.54+22.305 expected 58.845, actual 58.845 ----- OK
{
"RATE_1": 36.54,
"RATE_2": 22.305
}

Not very consistent..........which would be determined wrongly as false when using it in "==" like

{"===":[
{
      "+": [
        { "var": "RATE_1" },
        { "var": "RATE_2" }
      ]
},{"var":"TOTAL"}]
}
with data
{
"RATE_1": 36.54,
"RATE_2": 22.309,
"TOTAL": 58.849
}

**Comment by jwadhams** [comment]
That's not caused by JsonLogic, it's caused by floating point arithmetic. JsonLogic just delegates arithmetic to the implementing language, so this is going to act this way in any language that doesn't have built in Arbitrary Precision.

https://0.30000000000000004.com/
